### ISSUE TITLE
Crash when deploying blueprint with one tile of concrete

### ISSUE THREAD

**Issue by Kuinox** [justarandomgeek/factorio-bad-chest#6]
Hi,  
I have this error when i deploy a blueprint with one tile of concrete. 
http://i.imgur.com/u3Zcchw.png
Thanks !

**Comment by justarandomgeek** [comment]
You seem to be using an old version. Does this issue also occur with 0.2.6?

**Comment by Kuinox** [comment]
Oh, sorry, i was not on last version.
But the problem is still here, the error line changed too:
http://i.imgur.com/1o1UUo7.png

**Comment by justarandomgeek** [comment]
Hey, that line number makes way more sense... I'll post a fix shortly!

**Comment by Kuinox** [comment]
Thanks !

**Comment by justarandomgeek** [comment]
0.2.7 should fix this
